## Outbound Ports
twitter.api:
  url: https://api.twitter.com/2/
  bearer.token: ${TWITTER_BEARER_TOKEN}

logging:
  level:
    org.springframework.web: TRACE
    org.springframework.http: TRACE
    reactor.core: TRACE
    io.netty: TRACE
