## Outbound Ports
twitter.api:
  url: https://api.twitter.com/2/
  bearer.token: ${TWITTER_BEARER_TOKEN}

logging:
  level:
    org.springframework:
      web: TRACE
      cloud: TRACE
    com.github.tomakehurst.wiremock: TRACE
